# config.yaml
retrieval:
  method: hybrid
  semantic_weight: 0.5
  top_k: 100
  semantic_k: 50  # not actually used, just shows default value
  lexical_k: 50 # not actually used, just shows default value
  min_docs: 0
  max_docs: 10
  threshold: 0.3 # conservative thres


model:
  # default settings, backward compatibility
  type: "chatui"    # or "hf"
  hf_model: "https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-8B-Instruct"
  chatui_model: "llama3:8b" #llama3.2:1b" or "llama3:8b"

  # All available models, grouped by provider
  providers:
    chatui:
      default: "Llama-3.8-1B"
      options:
        - name: "Llama-3.2-1B"
          id:   "llama3.2:1b"
        - name: "Llama-3-8B"
          id:   "llama3:8b"
    hf:
      default: "Llama-3-8B"
      options:
        - name: "Llama-3-8B"
          id:   "https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-8B-Instruct"
        - name: "Llama-3-70B"
          id:   "https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-70B-Instruct"

generation:
  n_samples: 5       # number of samples to draw; 0 triggers dummy/demo
  #top_k: 5           # number of docs to retrieve
  temperature: 0.9   # sampling temperature
  top_p: 0.95        # nucleus sampling
  max_new_tokens: 300

# raw score -> higher is more uncertain
uncertainty: 

  method: "lexical_similarity" # default

  scaling:
    type: "quantile"               # or "isotonic"
    
    # for each UE method, point to the fitted‐scaler on disk
    paths:
      lexical_similarity: "data/fitted_scalers/lex_score_quantile_scaler.joblib"
      deg_mat: "data/fitted_scalers/deg_score_quantile_scaler.joblib"
      eccentricity: "data/fitted_scalers/ecc_score_quantile_scaler.joblib"

  lexical_similarity:
    metric: "rougeL"
  deg_mat:
    batch_size: 10
    device: "cpu"
    affinity: "entail"
    verbose: True
  eccentricity: 
    similarity_score: "NLI_score"
    affinity: "entail"
    verbose: True
    thres: 0.7 # paper default of 0.9, doesn't work with only 5 samples. should ideally be calibrated carefully

